spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306
        username: app
        password: app!@#

    jpa:
        hibernate:
            ddl-auto: create
